<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>CollegeERP_.Application</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="DTOs\.Courses\CreateCourseRequest.cs" />
    <Compile Include="DTOs\.Courses\GetCourseResponse.cs" />
    <Compile Include="DTOs\.Courses\UpdateCourseRequest.cs" />
    <Compile Include="DTOs\.Department\CreateDepartmentDTO.cs" />
    <Compile Include="DTOs\.Department\CreateDepartmentResponseDTO.cs" />
    <Compile Include="DTOs\.Department\DepartmentDTO.cs" />
    <Compile Include="DTOs\.Department\UpdateDepartmentRequest.cs" />
    <Compile Include="DTOs\.Student\CreateStudentRequest.cs" />
    <Compile Include="DTOs\.Student\GetStudentResponse.cs" />
    <Compile Include="DTOs\.Student\UpdateStudentRequest.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CollegeERP .Common\CollegeERP .Common.csproj" />
    <ProjectReference Include="..\CollegeERP.Domain\CollegeERP.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Mappings\" />
  </ItemGroup>

</Project>
